### ISSUE TITLE
Tensorflow 2.0 ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis.

### ISSUE THREAD

**Issue by iamrishab** [soumik12345/Nearest-Celebrity-Face#17]
I tried to run the code after porting it to Tensorflow 2.0 and for that, I only made changes in the imports. But while creating the model object it throws an error for shape mismatch in feature concatenation operation in `inception_block_1a`. Can you please check?

**Environment:**
Python==3.6.8
Tensorflow==2.1.0

But I think the environment has nothing to do with shape mismatch in the model.

**Full traceback of the error:**

`Traceback (most recent call last):
  File "inception_blocks_v2.py", line 270, in <module>
    inception_resnet_v2((3, 96, 96))
  File "inception_blocks_v2.py", line 246, in inception_resnet_v2
    X = inception_block_1b(X)
  File "inception_blocks_v2.py", line 75, in inception_block_1b
    inception = concatenate([X_3x3, X_5x5, X_pool, X_1x1], axis=-1)
  File "/home/rishab/anaconda3/envs/fr_env/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/merge.py", line 716, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/rishab/anaconda3/envs/fr_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 748, in __call__
    self._maybe_build(inputs)
  File "/home/rishab/anaconda3/envs/fr_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2116, in _maybe_build
    self.build(input_shapes)
  File "/home/rishab/anaconda3/envs/fr_env/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 306, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/rishab/anaconda3/envs/fr_env/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/merge.py", line 401, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 12, 12), (None, 64, 12, 12), (None, 64, 12, 12), (None, 64, 12, 12)]`

Thanks in advance.
Any help is appreciated.

**Comment by soumik12345** [comment]
@iamrishab Please refer to the `requirements.txt` file for the required dependencies. This demo was not developed with Tensorflow 2.x
